# Generated by Django 5.2.1 on 2025-05-20 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('color', models.CharField(default='#4CAF50', max_length=20, verbose_name='Цвет для отображения')),
            ],
            options={
                'verbose_name': 'Категория мест',
                'verbose_name_plural': 'Категории мест',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заведения')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='venue_layouts/', verbose_name='Схема зала')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Места проведения',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.venue', verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('number', models.PositiveIntegerField(verbose_name='Номер места')),
                ('x_coord', models.PositiveIntegerField(blank=True, null=True, verbose_name='Координата X')),
                ('y_coord', models.PositiveIntegerField(blank=True, null=True, verbose_name='Координата Y')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронировано')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Если не указана, будет использована цена из категории или события', null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.seatcategory', verbose_name='Категория места')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.venue', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['row', 'number'],
                'unique_together': {('venue', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True, verbose_name='Время бронирования')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.event', verbose_name='Мероприятие')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seat', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'unique_together': {('event', 'seat')},
            },
        ),
    ]
